"""update delete  subscriptions

Revision ID: 05fb91d5d68f
Revises: 9667d122321f
Create Date: 2025-03-28 14:39:01.180329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fb91d5d68f'
down_revision: Union[str, None] = '9667d122321f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('minute_subscriptions_id_fkey', 'minute_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'minute_subscriptions', 'subscriptions', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'minute_subscriptions', type_='foreignkey')
    op.create_foreign_key('minute_subscriptions_id_fkey', 'minute_subscriptions', 'subscriptions', ['id'], ['id'])
    # ### end Alembic commands ###
