"""update phone

Revision ID: 945828ec00cb
Revises: 8aeb4d878177
Create Date: 2025-03-26 03:01:14.635930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945828ec00cb'
down_revision: Union[str, None] = '8aeb4d878177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_phone_key', 'clients', type_='unique')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_unique_constraint('clients_phone_key', 'clients', ['phone'])
    # ### end Alembic commands ###
