"""update without period subscriptions

Revision ID: ccb6b3acaf35
Revises: 05fb91d5d68f
Create Date: 2025-03-29 11:36:33.965544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccb6b3acaf35'
down_revision: Union[str, None] = '05fb91d5d68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unlimited_subscriptions', 'period',
               existing_type=postgresql.ENUM('MONTH', 'HALF_YEAR', 'YEAR', name='periodtypes'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unlimited_subscriptions', 'period',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MONTH', 'HALF_YEAR', 'YEAR', name='periodtypes'),
               nullable=True)
    # ### end Alembic commands ###
